### ISSUE TITLE
SaintCoinach breaks on launch

### ISSUE THREAD

**Issue by RoelDevs** [xivapi/SaintCoinach#60]
Just downloaded the program but everytime I try to to run the .exe it shows a blank CMD box for the .exe and then quickly closes again. Probably crashing in some form and I can't find a way to fix it. Tried older versions and Admin mode/firewall allowance.

**Comment by goaaats** [comment]
SaintCoinach.Cmd is a command line app 

https://www.computerhope.com/issues/chusedos.htm

**Comment by CrimsonOrion** [comment]
I know this issue is closed, as it's not really an issue, but I can shed some light on it.
The command line program is looking for your ffxiv /boot/ directory either in program files, program files (x86), or from the app.config location.

You can fix this by going to the app.config file under <applicationSettings>. You'll see a setting called "DataPath". Change the value under it from `<value/>` to `<value>C:\WhateverYourFolderPathToFFXIV\FINAL FANTASY XIV - A Realm Reborn</value>`

The program is displaying an error "Need data!  The path '{dataPath}' doesn't exist.", but the window closes after it's displayed, so you don't see it. Perhaps we should add `Console.ReadKey()` after the WriteLine?
Anyway, I hope you get this and it helps others.
